@config
@author=Piet Mondriaan
@converter=Dirk Roorda (Text-Fabric)
@dateWritten=2023-04-24T19:35:41Z
@descriptionTf=Critical edition
@fmt:text-orig-full={str}{after}
@institute1=HuC
@institute2=Huygens
@institute3=RKD
@institute_contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@institute_contributors2=Leo Jansen, Peter Boot, Beatrice Nava, Mariken Teeuwen
@institute_contributors3=Wietse Coppes, Sabine Craft-Giepmans, Reinier van 't Zelfde
@institute_name1=Humanities Cluster
@institute_name2=Huygens Instituut
@institute_name3=Nederlands Instituut voor Kunstgeschiedenis
@institute_place1=Amsterdam
@institute_place2=Amsterdam
@institute_place3=Den Haag
@language=nl
@levelConstraints=note < chunk, p; salute < opener, closer; revisionDesc < chunk; facsimile < chunk; fileDesc < chunk; profileDesc < chunk; div < chunk
@schema=MD
@sectionFeatures=folder,letter,chunk
@sectionTypes=folder,letter,chunk
@sourceFormat=TEI
@title=Letters
@version=0.8.2pre
@writtenBy=Text-Fabric
@writtenBy=Text-Fabric
@dateWritten=2023-04-24T19:35:52Z

